set_property SRC_FILE_INFO {cfile:/home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_66/system_proc_sys_reset_0.xdc rfile:../../../.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_66/system_proc_sys_reset_0.xdc id:1 order:EARLY scoped_inst:ps/system_i/proc_sys_reset/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_processing_system7_0_66/system_processing_system7_0.xdc rfile:../../../.srcs/sources_1/bd/system/ip/system_processing_system7_0_66/system_processing_system7_0.xdc id:2 order:EARLY scoped_inst:ps/system_i/processing_system7/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jzsmith/git/RedPitaya/fpga/sdc/red_pitaya.xdc rfile:../../../../../sdc/red_pitaya.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list ps/system_i/proc_sys_reset/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D ps/system_i/proc_sys_reset/U0/EXT_LPF/ACTIVE_LOW_EXT.ACT_LO_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
current_instance ps/system_i/processing_system7/inst
set_property src_info {type:SCOPED_XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name clk_fpga_0 [get_pins {PS7_i/FCLKCLK[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name clk_fpga_1 [get_pins {PS7_i/FCLKCLK[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name clk_fpga_2 [get_pins {PS7_i/FCLKCLK[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name clk_fpga_3 [get_pins {PS7_i/FCLKCLK[3]}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[53]}]
set_property src_info {type:SCOPED_XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[52]}]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[51]}]
set_property src_info {type:SCOPED_XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[50]}]
set_property src_info {type:SCOPED_XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[49]}]
set_property src_info {type:SCOPED_XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[48]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[47]}]
set_property src_info {type:SCOPED_XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[46]}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[45]}]
set_property src_info {type:SCOPED_XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[44]}]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[43]}]
set_property src_info {type:SCOPED_XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[42]}]
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[41]}]
set_property src_info {type:SCOPED_XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[40]}]
set_property src_info {type:SCOPED_XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[39]}]
set_property src_info {type:SCOPED_XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[39]}]
set_property src_info {type:SCOPED_XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[39]}]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[39]}]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[38]}]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[38]}]
set_property src_info {type:SCOPED_XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[38]}]
set_property src_info {type:SCOPED_XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[38]}]
set_property src_info {type:SCOPED_XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[37]}]
set_property src_info {type:SCOPED_XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[37]}]
set_property src_info {type:SCOPED_XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[37]}]
set_property src_info {type:SCOPED_XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[37]}]
set_property src_info {type:SCOPED_XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[36]}]
set_property src_info {type:SCOPED_XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[36]}]
set_property src_info {type:SCOPED_XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[36]}]
set_property src_info {type:SCOPED_XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[36]}]
set_property src_info {type:SCOPED_XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[35]}]
set_property src_info {type:SCOPED_XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[35]}]
set_property src_info {type:SCOPED_XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[35]}]
set_property src_info {type:SCOPED_XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[35]}]
set_property src_info {type:SCOPED_XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[34]}]
set_property src_info {type:SCOPED_XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[34]}]
set_property src_info {type:SCOPED_XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[34]}]
set_property src_info {type:SCOPED_XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[34]}]
set_property src_info {type:SCOPED_XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[33]}]
set_property src_info {type:SCOPED_XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[33]}]
set_property src_info {type:SCOPED_XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[33]}]
set_property src_info {type:SCOPED_XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[33]}]
set_property src_info {type:SCOPED_XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[32]}]
set_property src_info {type:SCOPED_XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[32]}]
set_property src_info {type:SCOPED_XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[32]}]
set_property src_info {type:SCOPED_XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[32]}]
set_property src_info {type:SCOPED_XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {FIXED_IO_mio[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {FIXED_IO_mio[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports {FIXED_IO_mio[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {FIXED_IO_mio[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {FIXED_IO_mio[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrp]
set_property src_info {type:SCOPED_XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports FIXED_IO_ddr_vrn]
set_property src_info {type:SCOPED_XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_odt]
set_property src_info {type:SCOPED_XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports DDR_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:596 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION BIDIR [get_ports {DDR_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:2 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:2 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cs_n]
set_property src_info {type:SCOPED_XDC file:2 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:2 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:2 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cke]
set_property src_info {type:SCOPED_XDC file:2 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:2 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:2 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_p]
set_property src_info {type:SCOPED_XDC file:2 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:2 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:2 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION INPUT [get_ports DDR_ck_n]
set_property src_info {type:SCOPED_XDC file:2 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports DDR_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:630 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:665 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:669 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:671 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:678 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:689 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:690 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property PIO_DIRECTION OUTPUT [get_ports {DDR_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_porb]
set_property src_info {type:SCOPED_XDC file:2 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ps_porb]
set_property src_info {type:SCOPED_XDC file:2 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports FIXED_IO_ps_srstb]
set_property src_info {type:SCOPED_XDC file:2 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ps_srstb]
set_property src_info {type:SCOPED_XDC file:2 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports FIXED_IO_ps_clk]
set_property src_info {type:SCOPED_XDC file:2 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports FIXED_IO_ps_clk]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_dat_i[*][*]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc_clk_i[*]}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_clk_o[*]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {adc_clk_o[*]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {adc_clk_o[*]}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports adc_cdcs_o]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports adc_cdcs_o]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports adc_cdcs_o]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dat_o[*]}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {dac_dat_o[*]}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {dac_dat_o[*]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk_o]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports dac_rst_o]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sel_o]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports dac_wrt_o]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports dac_*_o]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports dac_clk_o]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports dac_rst_o]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports dac_sel_o]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports dac_wrt_o]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {dac_pwm_o[*]}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {dac_pwm_o[*]}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 12 [get_ports {dac_pwm_o[*]}]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vinp_i[*]}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vinn_i[*]}]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {exp_p_io[*]}]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {exp_n_io[*]}]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {exp_p_io[*]}]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {exp_n_io[*]}]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {exp_p_io[*]}]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 8 [get_ports {exp_n_io[*]}]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {daisy_p_o[*]}]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {daisy_n_o[*]}]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {daisy_p_i[*]}]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {daisy_n_i[*]}]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[*]}]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports {led_o[*]}]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 4 [get_ports {led_o[*]}]
set_property src_info {type:XDC file:3 line:206 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name adc_clk [get_ports {adc_clk_i[1]}]
set_property src_info {type:XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock adc_clk 3.400 [get_ports {adc_dat_i[*][*]}]
set_property src_info {type:XDC file:3 line:210 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 -name rx_clk [get_ports {daisy_p_i[1]}]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_fb -source [get_pins pll/pll/CLKIN1] -multiply_by 1 -add -master_clock adc_clk [get_pins pll/pll/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_adc_clk -source [get_pins pll/pll/CLKIN1] -multiply_by 1 -add -master_clock adc_clk [get_pins pll/pll/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_dac_clk_1x -source [get_pins pll/pll/CLKIN1] -multiply_by 1 -add -master_clock adc_clk [get_pins pll/pll/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_dac_clk_2x -source [get_pins pll/pll/CLKIN1] -multiply_by 2 -add -master_clock adc_clk [get_pins pll/pll/CLKOUT2]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_dac_clk_2p -source [get_pins pll/pll/CLKIN1] -edges {1 2 3} -edge_shift {-0.500 -2.500 -4.500} -add -master_clock adc_clk [get_pins pll/pll/CLKOUT3]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_ser_clk -source [get_pins pll/pll/CLKIN1] -multiply_by 2 -add -master_clock adc_clk [get_pins pll/pll/CLKOUT4]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name pll_pwm_clk -source [get_pins pll/pll/CLKIN1] -multiply_by 2 -add -master_clock adc_clk [get_pins pll/pll/CLKOUT5]
set_property src_info {type:XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks adc_clk]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/axi_protocol_converter_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/proc_sys_reset]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/processing_system7]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/xadc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/xlconstant]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/proc_sys_reset/U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/processing_system7/inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ps/system_i/xadc/inst]
