# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-23567-jzsmith-VirtualBox/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/ec67/hdl {
      /home/jzsmith/git/RedPitaya/fpga/rtl/evn_pkg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/sys_bus_interconnect.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/pdm.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_slave.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/lin_add.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/pid_block.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/str_dec.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/osc.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_stream_mux.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/top_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/old_asg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/ctrg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/str2mm.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/osc_trg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_asg_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/old_acq.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/sys_reg_array_o.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/rle.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/clkdiv.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_stream_cnt.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_pwm_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_pll.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/cts.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/old_id.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_ams_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_pwm.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/id.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/pid.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/asg_bst.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_pid_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_scope_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/clb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/pwm.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/asg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/muxctl.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_hk_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_stream_reg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/bin_and.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_stream_pas.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_stream_dly.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/la.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/sys_bus_stub.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/scope_dec_avg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/scope_filter.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/old_asg_top.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/lg.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/debounce.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/interface/axi4_stream_if.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/interface/gpio_if.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/interface/axi4_if.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/interface/spi_if.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/interface/sys_bus_if.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/interface/axi4_lite_if.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_dfilt1.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/gen.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/lin_mul.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_stream_demux.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/mgmt.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/asg_per.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_dfilt1_tb.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/acq.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/old_la_top.sv
      /home/jzsmith/git/RedPitaya/fpga/rtl/la_trg.sv
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/rtl/red_pitaya_ps.sv
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/rtl/red_pitaya_top.sv
      /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/ec67/hdl {
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0_66/synth/system_axi_protocol_converter_0_0.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_processing_system7_0_66/hdl/verilog/processing_system7_v5_5_processing_system7.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_processing_system7_0_66/synth/system_processing_system7_0.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/system_xadc_0.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xlconstant_0_66/synth/system_xlconstant_0.v
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/synth/system.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/axi4_lite_slave.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_pid.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_id.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_asg_ch.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_pid_block.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_scope.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/axi_wr_fifo.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_ams.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/axi_master.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_hk.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/classic/red_pitaya_asg.v
      /home/jzsmith/git/RedPitaya/fpga/rtl/red_pitaya_scope_tb.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_1 /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/67d8/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_2 /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/7aff/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_12 /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_66/synth/system_proc_sys_reset_0.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_conv_funs_pkg.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_proc_common_pkg.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_ipif_pkg.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_family_support.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_family.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_soft_reset.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_0_pselect_f.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_address_decoder.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_slave_attachment.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/interrupt_control_v2_01_a/hdl/src/vhdl/system_xadc_0_interrupt_control.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_0_axi_lite_ipif.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/system_xadc_0_xadc_core_drp.vhd
      /home/jzsmith/git/RedPitaya/fpga/prj/classic/.srcs/sources_1/bd/system/ip/system_xadc_0_66/system_xadc_0_axi_xadc.vhd
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-23567-jzsmith-VirtualBox/realtime/red_pitaya_top_synth.xdc
    rt::sdcChecksum
    set rt::top red_pitaya_top
    rt::set_parameter enableIncremental true
    set rt::flattenHierarchy 3
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter maxClockBufferCount 16
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops false
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-23567-jzsmith-VirtualBox/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-23567-jzsmith-VirtualBox/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -param {{ GITH 160'h\"735e9f30e7a6696f7544b7787bc6b9b6fdd2f1f4\" }} -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
